[package]
name = "pd_server"
version = "0.1.0"
authors = ["Ben Brunton <ben.brunton@infinityworks.com>"]

[dependencies.iron]
version = "*"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[dependencies.logger]
git = "https://github.com/iron/logger.git"

[dependencies]
router = "*"
toml = "0.2"
hyper = "0.9.10"
rustc-serialize = "0.3"
